name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GmsCore
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: GmsCore
      - name: Build GmsCore
        working-directory: GmsCore
        run: |
          echo 'mapbox.key=dummy' > local.properties
          ./gradlew --no-daemon build
        env:
          TERM: dumb
          JAVA_OPTS: -Xmx2048m
